### ISSUE TITLE
Nextcloud 25 and php8 support

### ISSUE THREAD

**Issue by mwinkens** [clarin-eric/B2Drop2LRS#12]
Currently the app is only available up to nextcloud 24. In the future we want to upgrade to nextcloud 25 with php8. We don't know if the app is capable of it, maybe you check it or you add a github pipline, similar to [this app as reference](https://github.com/EUDAT-B2DROP/b2sharebridge/blob/master/.github/workflows/build.yaml).

**Comment by mwinkens** [comment]
Same now for Nextcloud 26

**Comment by andmor-** [comment]
Done. 

Notes:
- The application name changed from "switchboardBridge" to "switchboardbridge"
- The default name for this repository changed to "B2Drop2LRS"
- The application is now compatible up to Nextcloud 26
- The project is now built using npm with @nextcloud/webpack-vue-config
- The code automatically fixed by the CI workflow is also automatically commited if the "deploy" test job succeeds

To test against other versions you can fork the repository and change any [workflow matrix](https://github.com/clarin-eric/B2Drop2LRS/blob/master/.github/workflows/main.yml). You can also make PRs upstream for things you are interested on.

**Comment by mwinkens** [comment]
Great work :+1:  can you create a new release candidate?

> Given the radical changes / deletions from the b2sharebridge code, its git log history has been deleted.
Sorry :see_no_evil:

**Comment by andmor-** [comment]
Here: https://github.com/clarin-eric/B2Drop2LRS/releases/tag/2.1-RC1
